- CHANGELOG.md
- Tempura/UITests/UITests.swift
Landscape and portrait ui tests were located in different folders, which doesn't make much sense as you want to look at a certain device screenshots. This PR fixes it
> Fix landscape issue with uitest folders

- CHANGELOG.md
- Tempura/UITests/UITestCase.swift
Adds orientation support for `UITestCase`. The test case will also wait for orientation to actually change, and avoid issues during snapshots
> Orientation support

- CHANGELOG.md
- Tempura/Navigation/Navigator.swift
In the past, we decided we wanted to support transparently hiding a view that is not being shown. However, the promise inside `hide` does not resolve if that is the case, leaving anyone awaiting for it stuck forever.
> [Fix] Fixed unresolving promise if calling `hide` on a view that is not in the `currentRoutables`

- CHANGELOG.md
- Tempura/UITests/ViewTestCase.swift
This fixes a broken UITest filename for the scrollable content snapshot.
> [Fix] Scrollable View UITest filename

- Tempura/Navigation/RootInstaller.swift
**Why**
To make sure we can pass it to external functions rather than restricting us to use it only inside the `instalRoot(identifier:context:completion:)` function body.
**Changes**
No major changes, just added the `@escaping` keyword before the closure type.
**Tasks**
> [Feature] Make closure in installRoot escaping

- Podfile.lock
- Tempura/UITests/UITests.swift
**Why**
This PR removes the following instructions:
`self.automaticallyAdjustsScrollViewInsets = false`
`self.edgesForExtendedLayout = []`
from inside the UITestCase implementation, that modified the insets of scrollViews to avoid them being drawn under navigation bars or tab bars. This is not always the desired behaviour of a view, so its UITests would create a wrong screenshot with respect to the real behaviour. If this behaviour is desired for a particular `ViewTestCase`, the same code can be added through the `.viewDidLoad` hook.
**Changes**
No API change, just removed the mentioned lines from the internal implementation of `HookableViewController`.
> [Fix] Remove custom edges behavior from HookableViewController

- CHANGELOG.md
- Tempura/UITests/UITests.swift
- Tempura/UITests/UIView+snapshot.swift
- Tempura/UITests/ViewControllerTestCase.swift
- Tempura/UITests/ViewTestCase.swift
**Why**
This PR adds the support to show the Safe Area insets in UITests.
**Changes**
New property `renderSafeArea` in Context (both for Views and ViewControllers)
**Tasks**
> [Feat] Add mock Safe Area Insets to UITests

- Tempura/Navigation/Navigator.swift
**Why**
This PR is needed to let custom ViewControllers that use the containment UIKit's APIs expose their Childs in order to propagate routing and presentation sources. This way they can be recognized from Tempura as Routable View Controllers.
**Changes**
Made `CustomRouteInspectables` and `RouteInspectable` public
**Tasks**
> [Feature] Public Access Level to Route Inspectables

- DemoTests/DemoTests.swift
- Podfile.lock
- README.md
- Tempura.xcodeproj/project.pbxproj
- Tempura.xcodeproj/xcshareddata/xcschemes/Demo.xcscheme
- Tempura.xcodeproj/xcshareddata/xcschemes/Tempura.xcscheme
- Tempura.xcodeproj/xcshareddata/xcschemes/TempuraTesting.xcscheme
- Tempura/UITests/UITests.swift
- Tempura/UITests/UIView+snapshot.swift
- Tempura/UITests/ViewControllerTestCase.swift
**Why**
In the current implementation, the `configure` method is called after the isViewReady, but in some cases we might want to wait some time after the configuration (e.g. to download a remote image)
**Changes**
ViewControllerTestCase uiTest method now accepts a dictionary of testId to VM.
The default configure implementation just sets the given VM to the view.
Instances of the same ViewControllerTestCase are now executed serially:
- configure of the first instance is called
- wait until isViewReady of the first instance is called
- take the snapshot
- configure of the second instance is called
- wait until isViewReady of the second instance is called
- take the snapshot
- ...
The ViewControllerTestCase.configure method is now called at the beginning of the test
**Tasks**
> Support to waiting for view to be ready after configure in ViewControllerTestCase

- DemoTests/DemoTests.swift
- README.md
- Tempura/UITests/UITests.swift
- Tempura/UITests/UIView+snapshot.swift
- Tempura/UITests/ViewControllerTestCase.swift
- Tempura/UITests/ViewTestCase.swift
**Why**
Some times in the UITests we want to test scenarios in which the keyboard is shown, but there is no way to render an actual keyboard in UITests
**Changes**
Added `keyboardVisibilty` callback in `UITests.Context` and `UITests.VCContext` which can be used to decide wether the keyboard should be displayed or not.
An alternative to put it in the context would be to put it as a function in ViewTestCase and ViewControllerTestCase, I have put it in the context for consistency with the renderSafeArea.
Possible values are: hidden (keyboard not shown), defaultHeight (keyboard shown with an height estimated from the device height and orientation), customHeight (keyboard shown with an user provided height)
If the provided keyboard height is not 0, a grey box of the given height is rendered at …
> Support for keyboard rendering

- DemoTests/DemoTests.swift
- README.md
- Tempura.xcodeproj/project.pbxproj
- Tempura.xcodeproj/xcshareddata/xcschemes/Demo.xcscheme
- Tempura.xcodeproj/xcshareddata/xcschemes/Tempura.xcscheme
- Tempura.xcodeproj/xcshareddata/xcschemes/TempuraTesting.xcscheme
- Tempura/UITests/UITests.swift
- Tempura/UITests/UIViewControllerTestCase.swift
- Tempura/UITests/ViewControllerTestCase.swift
- Tempura/UITests/ViewTestCase.swift
**Why**
Right now, with `ViewControllerTestCase` is impossible to test plain `UIViewController`s.
With this PR we are introducing two levels of VC testing:
- For a `ViewControllerTestCase` we introduce the concept of `TestableViewController`. A `ViewControllerTestCase` can be used to test a `TestableViewController`. 
A `TestableViewController` is a UIViewController that has a `rootView` of type `ModellableView`.
This is more generic than the previous `ViewControllerTestCase` implementation that was requiring the view to be a `ViewControllerModellableView`.
With this change, you can use a `ViewControllerTestCase` even if you have a simple `UIViewController` that is managing a `ModellableView`.
- A new `UIViewControllerTestCase` is introduced. With this test case, you can test …
> Ability to test vanilla UIViewControllers

- Tempura/UITests/UITests.swift
- Tempura/UITests/UIViewControllerTestCase.swift
- Tempura/UITests/ViewControllerTestCase.swift
**Why**
At the moment `TempuraTesting` lets you set a different `screen size` but actually it doesn't take into account this value.
This PR fixes the problem.
The `syncSnapshot` and `asyncSnapshot` method should expect a view with the frame already set.
**Tasks**
> Fix screenSize in UITests

- Tempura/Navigation/NavigationUtilities.swift
**Why**
If you have three VCs: A, B, C and try to soft-dismiss B using the DSL, you'll get stuck waiting for route to complete due to a missing call to completion.
**Changes**
Added missing completion call.
**Tasks**
> fix: missing completion

- Demo/UI/ListScreen/ListView.swift
**Why**
With the previous pinLayout, sendToArchiveButton was hidden in the UI.
**Changes**
Now the sendToArchiveButton button is visible in the UI and it is usable
**Tasks**
> fix: change pinLayout of sendToArchiveButton button in ListView

- Tempura/UITests/UITestCaseKeyValidator.swift
- Tempura/UITests/ViewControllerTestCase.swift
- Tempura/UITests/ViewTestCase.swift
**Why**
Executing the `uiTest` methods with duplicate keys causes previously created images to be overridden. This is usually undesirable and should be prevented programmatically.
**Changes**
A singleton `UITestCaseKeyValidator` instance for validating the uniqueness of UI test keys is introduced and used in the relevant methods.
> [Chore] Validate uniqueness of UI test keys

- README.md
the `ListView` example contained a duplicated line:
```
var todoButton: UIButton = UIButton(type: .custom)
```
**Tasks**
> Remove duplicated line in README.md

- README.md
**Why**
The purpose of this PR is updating the `README.md` to elicit the need to use [XCake](https://github.com/igor-makarov/xcake) to generate a project file a run the `Demo` app.
**Changes**
No code changes, just the `README.md` is impacted.
> Reference XCake in README.md

- Tempura/Navigation/Navigator.swift
**Why and Changes**
Fix a missing colon in documentation for navigator
> docs: add missing colon

- CHANGELOG.md
- Podfile.lock
- Tempura.podspec
- Tempura/Navigation/NavigationActions.swift
Based on #111 
**Why**
This ensures that:
- Tempura uses a version of Hydra compatible with Swift 5.5+.
- Tempura considers Hydra as an explicit dependency.
**Changes**
No API change
**Tasks**
> [Feat] Add Hydra 2.0.6 as explicit dependency

- CHANGELOG.md
- Tempura/Navigation/NavigationActions.swift
- Tempura/UITests/UITests.swift
- Tempura/UITests/ViewTestCase.swift
**Why**
Based on #113 
**Changes**
- Removed deprecated global `test` functions. The `ViewTestCase` API should be used instead.
- Removed `UITestCase` typealias. `ViewTestCase` should be used instead. No other changes should be necessary.
- Removed deprecated `dispatch` and `unsafeDispatch` for `NavigationSideEffect` on `AnyStore` and `AnySideEffectContext`. Katana's normal dispatch accepting `Dispatchable`s should be used instead.
- Removed `__unsafeDispatch` and `__unsafeAwaitDispatch` for `NavigationSideEffect` on `ViewController`. The base methods accepting `Dispatchable`s should be used instead.
**Tasks**
> [Feat] Remove deprecated APIs

- CHANGELOG.md
- Tempura/Sources/Navigation/Navigator.swift
**Why**
This PR allows the enriching of the `Navigation` object with a `RoutableProvider` to allow Tempura to handle its navigation without being the only manager of the app's navigation. 
This is needed when Tempura is added on top of another architecture that already has control of the navigation.
**Changes**
Enrich init of `Navigation` object with a `RoutableProvider` inited with a default value that is the live implementation.
**Tasks**
> [Feat] Witness navigation
